apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_NAME}}
  namespace: {{.Values.space_NAME}}
  labels:
    app: {{.Values.app_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app_NAME}}
  template:
    metadata:
      labels:
        app: {{.Values.app_NAME}}
    spec:
      containers:
        #container Java
        - image: nexus.sifast.com:8087/anapsix/alpine-java:8
          name: {{.Values.app_NAME}}
          imagePullPolicy: Always
          {{ if eq .Values.app_env "itg" }}
          command: ["/bin/sh", "-c", "java -jar /jar/springular.jar --spring.config.location=/jar/application-itg.properties"]
          {{ else if eq .Values.app_env "rec" }}
          command: ["/bin/sh", "-c", "java -jar /jar/springular.jar --spring.config.location=/jar/application-rec.properties"]
          {{ end }}

          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /jar
              name: jar-{{.Values.app_NAME}}-volume
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"

      volumes:
        - name: jar-{{.Values.app_NAME}}-volume
          persistentVolumeClaim:
            claimName: jar-{{.Values.app_NAME}}-volume

      imagePullSecrets:
        - name: docker-credentials-{{.Values.app_NAME}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: sifast-devops
                  operator: In
                  values:
                  - projects
