apiVersion: v1
kind: PersistentVolume
metadata:
  name: jar-{{.Values.app_NAME}}-volume
  namespace: {{.Values.space_NAME}}
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage-nfs.sifast.com
    path: /local_nfs/{{.Values.space_NAME}}/{{.Values.app_NAME}}/jar
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
