apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jar-{{.Values.app_NAME}}-volume
  namespace: {{.Values.space_NAME}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Mi
  volumeName: jar-{{.Values.app_NAME}}-volume
