package com.sifast.springular.framework.business.logic.common.constants;

public class Constants {

	public static final String PATTERN_DATE = "dd/MM/yyyy";
	public static final String DATE_WITH_DASH = "yyyy-MM-dd";
	public static final String DEFAULT_TIME_ZONE = "Africa/Tunis";
	public static final int MAX_STRING_SIZE = 200;
	public static final String PATTERN_TABULATION = "	";
	public static final String PATTERN_CMD_SH_OPTION_C = "-c";
	public static final String PATTERN_CMD_MYSQL_DB = "/Applications/xampp/xamppfiles/bin/mysql -uroot --execute \"create DATABASE ";
	public static final String PATTERN_GIT_CLONE = "git clone http://git.sifast.com/";
	public static final String PATTERN_POINT_GIT = ".git";
	public static final String PATTERN_POINT_VIRGULE = ";";
	public static final String PATTERN_SLASH = "/";
	public static final String PATTERN_ANTI_SLASH = "\"";
	public static final String PATTERN_DATABASE_NAME = "db_springular";
	public static final String PATTERN_DATABASE_USERNAME = "root";
	public static final String PATTERN_DATABASE_PASSWORD = "sifast2014";
	public static final String PATTERN_RETOUR_LIGNE = "\n";
	public static final String PATTERN_POINT_VIRGULE__ET_RETOUR_LIGNE = ";\n";
	public static final String ACCOLADE_OUVRANT = "{";
	public static final String ACCOLADE_FERMANTE = "}";
	public static final String NAME_PROJECT = "SpringularFrameworkSocle";
	public static final String ENABLE_DTO_GENERATION = "dto all with mapstruct";
	public static final String COMMAND_DELETE_FOLDER = "rm -r ";
	public static final String EXTEND_TIMESTAMP_ENTITY = "extends TimestampEntity implements";
	public static final String IMPLEMENTS = "implements";
	public static final String UNUSED_COMMENTS_FOR_ATTRIBUE = "// jhipster-needle-entity-add-field - JHipster will add fields here, do not remove";
	public static final String UNUSED_COMMENTS_FOR_METHOD = "// jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here, do not remove";
	public static final String SKIP_INSTALL_NODE_MODULES = "--skip-install";
	public static final String MKDIR_COMMAND = "mkdir ";
	public static final String INTERFACE_PUBLIC = "public interface ";
	public static final String IGENERIC_SERVICE = "IGenericService<";
	public static final String PUBLIC_CLASS = "public class ";
	public static final String GENERIC_SERVICE = " GenericService<";
	public static final String SUPRESS_WARNINGS_UNUSED = "(\"unused\")";
	public static final String SUPRESS_WARNINGS_UNUSED_PARENTHESE_OUVRANTE = "\\(";
	public static final String SUPRESS_WARNINGS_UNUSED_PARENTHESE_FERMANTE = "\\)";
	public static final String PUBLIC_INTERFACE = "public interface ";
	public static final String EXTENDS = " extends ";
	public static final String IGENERICDAO = "IGenericDao<";
	public static final String VIRGULE = ",";
	public static final String LONG = "Long>";
	public static final String PRIVATE = "private ";
	public static final String PUBLIC = "public ";
	public static final String RETURN = "return ";
	public static final String VOID = "void ";
	public static final String PARENTHESE_OUVRANTE = "(";
	public static final String PARENTHESE_FERMANTE = ")";
	public static final String THIS = "this.";
	public static final String EGALE = " = ";
	public static final String TO_STRING_METHOD = "public String toString() {\n";
	public static final String DECLARATION_STRING_BUILDER = "StringBuilder builder = new StringBuilder();\n";
	public static final String BUILDER_APPEND = "builder.append";
	public static final String RETURN_BUILDER_TO_STRING = "return builder.toString();\n";
	public static final String CROCHEE_FERMANTE = "]";
	public static final String CROCHEE_OUVRANTE = "[";
	public static final String DOUBLE_COTE = "\"";
	public static final String TEST_SET = "Set<";
	public static final String TEST_LIST = "List<";
	public static final String INFERIEUR = "<";
	public static final String ID = "Id";
	public static final String ID_MINUS = "id";
	public static final String SUPERIEUR = ">";
	public static final String POM_XML = "pom.xml";
	public static final String OLD_PROJECT_NAME = "springular-framework";
	public static final String OLD_PROJECT_NAME_ALT = "Springular Framework";
	public static final String OLD_PROJECT_NAME_TO_CLONE = "springular-framework-socle";
	public static final String APPLICATION_PROPERTIES_FILE = "application.properties";
	public static final String SWAGGER_CONFIG_FILE = "SwaggerConfig.java";
	public static final String POINT_ZIP = ".zip";
	public static final String METHODE_MAP = "modelMapper.map";
	public static final String POINT = ".";
	public static final String PARENTHESE_VALUE_EGALE_ACCOLADE="(value = {\n";
	public static final String PARENTHESE_CODE_EGALE="(code =";
	public static final String API_STATUS_ACCEPTED="ApiStatus.STATUS_ACCEPTED";
	public static final String API_MESSAGE="message = ApiMessage.";
	public static final String _CREATED_SUCCESSFULLY ="_CREATED_SUCCESSFULLY";
	public static final String RESPONSE_EGALE = "response = ";
	public static final String POINT_CLASS = ".class";
	public static final String API_STATUS_BAD_REQUEST = "ApiStatus.STATUS_BAD_REQUEST";
	public static final String INVALID_INPUT = "INVALID_INPUT";
	public static final String HTTP_ERROR_RESPONSE= "HttpErrorResponse";
	public static final String PARENTHESE_VALUE_EGALE="(value = ";
	public static final String METHOD_EGALE="method =";
	public static final String REQUEST_METHOD_POINT = "RequestMethod.";
	public static final String POST = "POST";
	public static final String RESPONSE_ENTITY = "ResponseEntity<Object> ";
	public static final String BINDING_RESULT = "BindingResult";
	public static final String GET = "GET";
	public static final String INT = "int";
	public static final String DELETE = "DELETE";
	public static final String PUT = "PUT";
	public static final String SLASH_API = "/api/";
	public static final String LOGGER = "private static final Logger LOGGER = LoggerFactory.getLogger";
	public static final String HTTP_ERROR_RESPONSE_DECLARATION = "private HttpErrorResponse httpErrorResponse = new HttpErrorResponse();\n";
	public static final String HTTP_RESPONSE_BODY_DECLARATION = "private Object httpResponseBody;\n";
	public static final String HTTP_HTTP_STATUS_DECLARATION = "private HttpStatus httpStatus;\n";
	public static final String FINDALL = "findAll"; 
	public static final String HTTP_STATUS_OK =	"httpStatus = HttpStatus.OK;\n";
	public static final String HTTP_RESPONSE_BODY = "httpResponseBody ";
	public static final String NOT="!";
	public static final String POINT_INTERROGATION=" ? ";
	public static final String IS_EMPTY = "isEmpty()";
	public static final String STREAM_METHOD = "stream()";
	public static final String MAP_METHOD = "map";
	public static final String FLECHE = "->";
	public static final String MODEL_MAPPER_VARIABLE= "modelMapper";
	public static final String COLLECT_METHOD = "collect";
	public static final String COLLECTORS_LIST = "Collectors.toList()";
	public static final String DEUX_POINTS = " : ";
	public static final String COLLECTIONS_EMPTY_LIST = "Collections.emptyList()";
	public static final String RETURN_WS="return new ResponseEntity<>(httpResponseBody, httpStatus);\n";
	public static final String REQUIRED_EGALE_TRUE = " required = true ";
	public static final String ALLOWABLE_VALUES = "allowableValues = \"range[1,infinity]\"";
	public static final String LOGGER_INFO = "LOGGER.info";
	public static final String OPTIONAL="Optional";
	public static final String FIND_BY_ID = "findById";
	public static final String IF = "if ";
	public static final String IS_PRESENT_METHOD = "isPresent()";
	public static final String DELETE_METHOD = "delete";
	public static final String GET_METHOD = "get()";
	public static final String HTTP_STATUS_NOT_FOUND ="httpStatus = HttpStatus.NOT_FOUND;\n";
	public static final String ELSE = "else ";
	public static final String HTTP_RESPONSE_BODY_EGALE_HTTP_ERROR_RESPONSE= "httpResponseBody = httpErrorResponse;\n";
	public static final String HTTP_ERROR_RESPONSE_SET_CODE_AND_MESSAGE = "httpErrorResponse.setHttpCodeAndMessage(HttpCostumCode.NOT_FOUND.getValue(), ApiMessage.";
	public static final String _NOT_FOUND="_NOT_FOUND";
	public static final String CONSTANTS_DECLARATION = "public static final String ";
}
