package com.sifast.springular.framework.business.logic.common;

public class Constants {

	public static final String PATTERN_DATE = "dd/MM/yyyy";
	public static final String PDF_EXTENSION = ".pdf";
	public static final String DEFAULT_AUTHORITY = "AUTH_VIEW_LANDING_PAGE";
	public static final String DATE_WITH_DASH = "yyyy-MM-dd";
	public static final String DEFAULT_TIME_ZONE = "Africa/Tunis";
	public static final int MAX_STRING_SIZE = 200;
	public static final String PATTERN_TABULATION = "	";
	public static final String PATTERN_CMD_SH = "/bin/sh";
	public static final String PATTERN_CMD_ZSH = "/bin/zsh";
	public static final String PATTERN_CMD_SH_OPTION_C = "-c";
	public static final String PATTERN_CMD_MYSQL_DB = "/Applications/xampp/xamppfiles/bin/mysql -uroot --execute \"create DATABASE ";
	public static final String PATTERN_GIT_CLONE = "git clone http://git.sifast.com/";
	public static final String PATTERN_POINT_GIT = ".git";
	public static final String PATTERN_POINT_VIRGULE = ";";
	public static final String PATTERN_SLASH = "/";
	public static final String PATTERN_ANTI_SLASH = "\"";
	public static final String PATTERN_PATH_APPLICATION_PROPERTIES = "/Users/qc/Desktop/springular-framework/springular-framework-web/src/main/resources/application.properties";
	public static final String PATTERN_DATABASE_NAME = "db_springular";
	public static final String PATTERN_DATABASE_USERNAME = "root";
	public static final String PATTERN_DATABASE_PASSWORD = "sifast2014";
	public static final String PATTERN_RETOUR_LIGNE = "\n";
	public static final String PATTERN_POINT_VIRGULE__ET_RETOUR_LIGNE = ";\n";
	public static final String ACCOLADE_OUVRANT = "{";
	public static final String ACCOLADE_FERMANTE = "}";
	public static final String PATTERN_PATH_TO_PACKAGE_MODEL = "/Users/qc/Desktop/springular-framework/springular-framework-persistence/src/main/java/com/sifast/model";
	public static final String PATTERN_PACKAGE_NAME = "com.sifast.springular.framework";
	public static final String COPY_COMMAND_WINDOWS = "copy -a ";
	public static final String COPY_COMMAND_LINUX = "cp -a ";
	public static final String COPY_COMMAND_LINUX_FILES = "mv ";
	public static final String PATH_TO_SPRINGULAR_FRAMEWORK_SOCLE_MODEL_PACKAGE = "/Users/qc/Desktop/springular-framework-socle/springular-framework-persistence/src/main/java/com/sifast/model/ ";
	public static final String PATH_TO_SPRINGULAR_FRAMEWORK_SOCLE_MODEL_PACKAGE_FILES = "/Users/qc/Desktop/springular-framework-socle/springular-framework-persistence/src/main/java/com/sifast/model/";
	public static final String PATH_TO_GENERATED_JHIPSTER_PROJECT = "/Users/qc/Desktop/testjdl/src/main/java/com/sifast/springular/framework/domain/ ";
	public static final String PATH_TO_GENERATED_JHIPSTER_PROJECT_FOR_FILES = "/Users/qc/Desktop/testjdl/src/main/java/com/sifast/springular/framework/domain/";
	public static final String PATH_TO_SPRINGULAR_FRAMEWORK_SOCLE = "/Users/qc/Desktop";
	public static final String NAME_PROJECT = "SpringularFrameworkSocle";
	public static final String ENABLE_DTO_GENERATION = "dto all with mapstruct";
	public static final String PATH_TO_CLONED_PROJECT_SOURCE = "/Users/qc/Documents/springular-framework/springular-framework-business-logic/springular-framework-socle ";
	public static final String COMMAND_DELETE_FOLDER = "rm -r";
	public static final String EXTEND_TIMESTAMP_ENTITY = "extends TimestampEntity implements";
	public static final String IMPLEMENTS = "implements";
	public static final String UNUSED_COMMENTS_FOR_ATTRIBUE = "// jhipster-needle-entity-add-field - JHipster will add fields here, do not remove";
	public static final String UNUSED_COMMENTS_FOR_METHOD = "// jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here, do not remove";
	public static final String ANNOTATION_NO_FLUENT_METHOD = "@noFluentMethod";
	public static final String SKIP_INSTALL_NODE_MODULES = "--skip-install";
	public static final String PACKAGE_JHIPSTER = "package com.sifast.springular.framework.domain;";
	public static final String PACKAGE_SPRINGULAR = "package com.sifast.model;\nimport com.sifast.model.TimestampEntity;";
}
